version: '3.8'
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_REPL_USER: ${DB_REPL_USER}
      DB_REPL_PASSWORD: ${DB_REPL_PASSWORD}
      DB_USER: ${DB_USER}
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
      POSTGRES_INITDB_ARGS: "--auth=scram-sha-256"
    env_file:
      - .env
    command: >
      postgres
      -c wal_level=replica
      -c hot_standby=on
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c hot_standby_feedback=on
      -c log_replication_commands=on
      -c logging_collector=on
      -c log_directory='/var/log/postgresql'
      -c log_destination='stderr'
      -c log_filename='logfile.log'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  db_repl:
    build:
      context: ./db_repl
      dockerfile: Dockerfile
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${DB_REPL_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    user: ${DB_USER}
    command: |
      bash -c "
      export PGPASSWORD=${DB_PASSWORD}
      until pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot --host=db --port=5432
      do
        echo 'Waiting for primary to connect...'
        sleep 1s
      done
      echo 'Backup done, starting replica...'
      chmod 0700 /var/lib/postgresql/data
      postgres
      "
    depends_on:
      - db

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - ./.env:/bot/.env:ro
    ports:
      - 5001:5000
    depends_on:
      - db
